### ISSUE TITLE
Fronted application npm start return error

### ISSUE THREAD

**Issue by GhettoBurger996** [Bennyhwanggggg/Marvel#2]
Hey there!

Installed and setup the application based on the documentation set. The backed section runs just fine but the fronted doesn't seem to want to run, not sure what the problem

``` at FSReqCallback.oncomplete (fs.js:184:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/joey/Downloads/Projects/Marvel-Encyclopedia/frontend/public',
  filename: '/home/joey/Downloads/Projects/Marvel-Encyclopedia/frontend/public'
}
npm ERR! code 1
npm ERR! path /home/joey/Downloads/Projects/Marvel-Encyclopedia/frontend
npm ERR! command failed
npm ERR! command sh -c react-scripts start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joey/.npm/_logs/2021-02-22T21_00_33_751Z-debug.log
```

Any help is much appreciated, thanks!

**Comment by GhettoBurger996** [comment]
here are the debug.logs if needed

```
0 verbose cli [
0 verbose cli   '/home/joey/.nvm/versions/node/v14.15.4/bin/node',
0 verbose cli   '/home/joey/.nvm/versions/node/v14.15.4/bin/npm',
0 verbose cli   'start'
0 verbose cli ]
1 info using npm@7.5.3
2 info using node@v14.15.4
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/home/joey/.nvm/versions/node/v14.15.4/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/joey/Downloads/Projects/Marvel-Encyclopedia/frontend/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/joey/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/home/joey/.nvm/versions/node/v14.15.4/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 6ms
19 verbose npm-session 0e70a09dfb44ba1e
20 timing npm:load Completed in 12ms
21 timing command:run-script Completed in 1524ms
22 timing command:start Completed in 1526ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/home/joey/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (events.js:315:20)
23 verbose stack     at maybeClose (internal/child_process.js:1048:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
24 verbose pkgid frontend@0.1.0
25 verbose cwd /home/joey/Downloads/Projects/Marvel-Encyclopedia/frontend
26 verbose Linux 5.4.0-65-generic
27 verbose argv "/home/joey/.nvm/versions/node/v14.15.4/bin/node" "/home/joey/.nvm/versions/node/v14.15.4/bin/npm" "start"
28 verbose node v14.15.4
29 verbose npm  v7.5.3
30 error code 1
31 error path /home/joey/Downloads/Projects/Marvel-Encyclopedia/frontend
32 error command failed
33 error command sh -c react-scripts start
34 verbose exit 1
```
